Reference for code: https://github.com/pjleimbigler/text-to-digraph/blob/main/notebooks/Text%20to%20diGraph.ipynb

In [3]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import seaborn as sns
import re

from collections import Counter

In [93]:
path = 'trump_tweets.csv'
data = pd.read_csv(path)
data.head()
data.text
#with open(path, 'r', encoding="utf8") as f:
    #lines = f.read()
# Remove parentheses and selected punctuation
lines = data.text.str.cat()
lines = re.sub('[\(\)\,\'"\?-]', ' ', lines).lower()
lines = lines.split()  # Defaults to treating consecutive whitespace (incl. line breaks) as single separator

In [95]:
edges = Counter(zip(lines[:-1], lines[1:]))
edges = pd.Series(edges).reset_index()
edges.columns = ['source', 'target', 'weight']
edges = edges.sort_values(['weight', 'source', 'target'], ascending=[0, 1, 1]).reset_index(drop=True)

In [96]:
edges.head(20)

    source target  weight
0       of    the    4127
1       in    the    3081
2     will     be    2661
3       is      a    2109
4       to    the    1951
5      for    the    1929
6       on    the    1677
7        a  great    1602
8       to     be    1389
9      and    the    1248
10      at    the    1241
11      is    the    1101
12   thank    you    1070
13      it     is     988
14      we    are     967
15    with    the     926
16  donald  trump     916
17   going     to     867
18     don      t     852
19    they    are     804

In [24]:
edges.head(20).to_csv('TrumpTweetsCommonWords20.csv', index=True, header=True)